name: ticktick_random_picker
description: A Flutter app that integrates with TickTick API to fetch todo lists and randomly pick tasks.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  oauth2: ^2.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.5
  flutter_secure_storage: ^6.0.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  random_color: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 